apiVersion: apps/v1
kind: Deployment
metadata:
  name: jewelry-backend-deployment
  namespace: roieharkavi-jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jewelry-backend
  template:
    metadata:
      annotations:
        # זה הפתרון לבעיית ה-Sync: גורם ל-K8s לרענן את הפודים גם כשה-Tag הוא latest
        kubectl.kubernetes.io/restartedAt: "2026-01-15T12:00:00Z"
      labels:
        app: jewelry-backend
    spec:
      containers:
        - name: backend-container
          image: 661659055102.dkr.ecr.us-east-1.amazonaws.com/jewelry-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: jewelry-backend-service
  namespace: roieharkavi-jenkins
spec:
  type: LoadBalancer
  selector:
    app: jewelry-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
