# --- JEWELRY BACKEND ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jewelry-backend-deployment
  namespace: roieharkavi-jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jewelry-backend
  template:
    metadata:
      annotations:
        # ערך קבוע למניעת קונפליקטים ב-Sync
        deployment-version: "2026-01-15-v1"
      labels:
        app: jewelry-backend
    spec:
      containers:
        - name: backend-container
          image: 661659055102.dkr.ecr.us-east-1.amazonaws.com/jewelry-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: jewelry-backend-service
  namespace: roieharkavi-jenkins
spec:
  type: LoadBalancer
  selector:
    app: jewelry-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
# --- AUTH SERVICE ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  namespace: roieharkavi-jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      annotations:
        deployment-version: "2026-01-15-v1"
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-container
        image: 661659055102.dkr.ecr.us-east-1.amazonaws.com/jewelry-auth:latest 
        ports:
        - containerPort: 8001
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: roieharkavi-jenkins
spec:
  type: LoadBalancer
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
