apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: roieharkavi-jenkins
spec:
  type: LoadBalancer
  selector:
    app: my-app  # וודא שזה תואם ל-label ב-Deployment שלך
  ports:
    - protocol: TCP
      port: 80         # הפורט שדרכו CloudFront יתחבר
      targetPort: 80   # הפורט שהאפליקציה שלך מאזינה לו בפועל
